[package]
name = "control_panel_gui"
version = "0.1.0"
edition = "2021"
default-run = "ctrl-panel"

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.7", package = "gtk4" }
adw = { version = "0.5", package = "libadwaita", features = ["v1_4"] }
gio = { version = "0.20.0", features = ["v2_74"] }
clap = { version = "4.4", features = ["derive"] }
regex = "1"

prost = "0.12"
tokio = {version = "1.0", features = ["rt-multi-thread", "time", "macros"]}
tokio-stream = "0.1"
tonic = {version="0.11.0", features = ["tls"]}
async-channel = "2.3"

givc-client = { git = "https://github.com/tiiuae/ghaf-givc", branch = "main" }
givc-common = { git = "https://github.com/tiiuae/ghaf-givc", branch = "main" }

[build-dependencies]
glib-build-tools = "0.19"
tonic-build = "0.11"

[[bin]]
name = "ctrl-panel"
path = "src/main.rs"
